name: CI/CD with Terraform

on:
  push:
    branches:
      - main  

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: ap-south-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${TF_STATE_BUCKET_NAME}" -backend-config="region=${AWS_REGION}"
        working-directory: ./terraform

      - name: Terraform Plan
        id: Plan
        run: |
          terraform plan \
          -var="region=${AWS_REGION}" \
          -var="public_key=${PUBLIC_SSH_KEY}" \
          -var="private_key=${PRIVATE_SSH_KEY}" \
          -var="key_name=todo-terraform" \
          -out=PLAN
        working-directory: ./terraform

      - name: Terraform Apply
        id: Apply
        run: terraform apply PLAN
        working-directory: ./terraform
